STATES = ["FINDING_WASTE","TRANSPORTING","SEARCHING_FOR_BOX"]

#FINDING WASTE = RANDOM WALK IF NOTHING ON INTERNAL MAP, OR GO TO CLOSEST IF SOMETHING ON THE MAP (WE DONT CARE ABOUT AGE YET)

#TRANSPORTING = YOU HAVE TRANSFORMED WASTE AND NOW HAVE TO GO TO THE EAST TO DEPOSE IT ON THE FRONTIER

#SEARCHING FOR BOX , ONLY FOR RED ROBOTS, TO SEE LATER